멀티모듈 및 FCM 세팅을 진행합니다.
pickly-team/pickly-backend pull request #2
Opened 2023-01-17 17:30 UTC by JoeCP17

사전 기획 나온대로 멀티모듈 세팅완료 

FCM 세팅완료 및 주석 작성 

프로젝트 적용항목 
Spring 3.0 
java 17

2023-01-18 11:25 UTC, aeong98 approved these changes
LGTMLGTMLGTM 멀티모듈의 신 의빈갓

2023-01-18 11:25 UTC, aeong98 commented on pickly-scheduler/src/main/resources/application-local.yml
> +server:
스케줄러 쪽만 port 넘버를 따로 지정해주신 이유가 궁금합니다!! 하하하하

2023-01-18 11:25 UTC, aeong98 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
이거 환경변수 각자 로컬에서 세팅해줘야되는건지 궁금합니다!! 하하하

2023-01-18 11:25 UTC, aeong98 commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +  INVALID_INPUT_VALUE(400, "C001", " Invalid Input Value"),
굳입니다아아아 👍

2023-01-18 11:43 UTC, litsynp requested changes
전반적으로 포매터 한 번 돌리면 좋을 것 같아요! 아직 @SoobinJung1013 이 CheckStyle 작업을 안해서 어차피 돌려야겠지만...ㅋㅋ

2023-01-18 11:43 UTC, litsynp commented on .gitignore
> +© 2022 GitHub, Inc.
이건 뭐죠..?!

2023-01-18 11:43 UTC, litsynp commented on pickly-common/src/main/java/org/pickly/common/error/GlobalExceptionHandler.java
> +
여기 두줄 띄었어요

2023-01-18 11:43 UTC, litsynp commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +
여기 두줄 띄었어요

2023-01-18 11:43 UTC, litsynp commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +    return this.message;
다른 곳은 this가 붙었는데 여긴 this가 붙었어요. 어느 쪽을 따르는게 좋을까요?

2023-01-18 11:43 UTC, litsynp commented on pickly-push/src/main/java/org/pickly/push/provider/FirebaseAppProvider.java
> +            if(firebaseApps.containsKey(projectName)) return firebaseApps.get(projectName);
여기 포매팅이 뭔가 안된 것 같아요

2023-01-18 11:43 UTC, litsynp commented on pickly-scheduler/src/main/resources/application-local.yml
> +server:
기본이 8080이라 하나는 안적고 여기는 명시해두신 것 같네요!

2023-01-18 12:08 UTC, SoobinJung1013 approved these changes
수고하셨습니다 ! 🙇🏻‍♂️

2023-01-18 13:40 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/ErrorResponse.java
> +  private String code;
ErrorResponse 포맷 고정인가요? 👀
Common Reponse와 Error Response 포맷은 개발 시작 전에 다같이 공유하면 좋을 것 같습니다!

2023-01-18 13:47 UTC, JoeCP17 commented on .gitignore
> +© 2022 GitHub, Inc.
.gitinore 시간을 절약하기 위해..... 다 가져와봤습니다

2023-01-18 13:53 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/GlobalExceptionHandler.java
> +    log.error("handleEntityNotFoundException", e);
이 로그는 예시인거죠?

2023-01-18 13:54 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +@JsonFormat(shape = JsonFormat.Shape.OBJECT)
추가해주신 이유 궁금합니다!

2023-01-18 13:55 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +    return this.message;
저는 개인적으로 this 있는게 좋아요ㅎ.ㅎ 다른 분들은 어떠신가요?

2023-01-18 13:56 UTC, JoeCP17 commented
전체적으로 승준님이 말씀해주셨던 포메팅 수정 적용하였습니다!

2023-01-18 13:59 UTC, EunjiShin commented on pickly-push/src/main/java/org/pickly/push/provider/FirebaseAppProvider.java
> +            return firebaseApps.get(projectName);
혹시 `private final Map<String, FirebaseApp> firebaseApps = new HashMap<>();` 의 용도는 무엇인가요?
firebaseApps에 뭐가 있던, 하나의 firebaseApp만 사용하게 되는 것 같아서요!

2023-01-18 14:02 UTC, ww8007 approved these changes
LGTM!

2023-01-18 14:02 UTC, ww8007 commented on pickly-common/src/main/java/org/pickly/common/error/ErrorResponse.java
> +    private int status;
요것도 상수화 처리가 가능한가요? 궁금해서요

2023-01-18 14:12 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/exception/EntityNotFoundException.java
> +}
어플리케이션 관련 exception은 BusinessException를 상속받아 처리하게 사용하는 예시가 맞을까요?
맞다면 BusinessException을 상속받아야 하는 이유가 있을까요?

2023-01-18 14:13 UTC, EunjiShin commented on gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
아니용! 그거 gradle 기본 세팅이에용 모두 동일함니다

2023-01-18 14:14 UTC, EunjiShin commented
고생하셨습니다! 역시 의빈갓 👍

2023-01-18 14:19 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +    HANDLE_ACCESS_DENIED(403, "C006", "Access is Denied");
Bad Request error를 "C001", "C003", "C005"로 세분화하신거죠? 

- status : ResponseEntity에서 Http status 넣어줄 때 사용
- code : 에러 세분화 -> FE 또는 디버깅할 때 사용
- message: 이해를 돕기 위함

위 의도 맞을까요?

2023-01-18 16:19 UTC, litsynp commented on pickly-scheduler/src/main/java/org/pickly/scheduler/SchedulerApplication.java
> +    }
이건 그냥 배치 세팅을 .yml에서 읽으려고 넣으신 것 같아요!

2023-01-18 16:20 UTC, litsynp commented on pickly-common/src/main/java/org/pickly/common/error/exception/EntityNotFoundException.java
> +}
`CheckedException`인 `RuntimeException`을 상속해 `BusinessException`을 공통 Exception으로 두려고 하신 것 같고,

상속을 이용해 생성자에서 메세지, 에러코드만 넣으려고 두신 것 같습니당

2023-01-19 01:03 UTC, JerryK026 commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +    return this.message;
저도 this 있는게 명시적으로 구분하기 좋아서 this 선호하는 편이에요!

2023-01-19 09:13 UTC, EunjiShin commented on pickly-common/src/main/java/org/pickly/common/error/exception/EntityNotFoundException.java
> +}
RuntimeException을 바로 상속받는게 낫지 않을까요? BusinessException으로 묶어야 하는 예시가 있을까요? 🤔

2023-01-19 11:56 UTC, litsynp commented on pickly-common/src/main/java/org/pickly/common/error/GlobalExceptionHandler.java
> +    log.error("handleEntityNotFoundException", e);
Exception handling 부분은 https://github.com/cheese10yun/spring-guide/blob/master/docs/exception-guide.md 여기 참고해서 가져온 걸로 알고 있어서 ㅋㅋ.. 필요에 따라 바꿔서 쓰셔도 될 듯 한데, 자세한 건 @JoeCP17 께 토스!

2023-01-19 11:58 UTC, litsynp commented on pickly-common/src/main/java/org/pickly/common/error/exception/EntityNotFoundException.java
> +}
모든 Exception에 HTTP status (+ `ErrorCode`)를 넣도록 강제 하려고 BusinessException으로 묶으신 듯 한데요,

- `EntityNotFoundException` -> `ENTITY_NOT_FOUND` (404)
- `InvalidValueException` -> `INVALID_INPUT_VALUE` (400)

이것도 PR 올려주신 @JoeCP17 님께 토스!

2023-01-19 12:55 UTC, JerryK026 commented on pickly-common/src/main/java/org/pickly/common/error/exception/EntityNotFoundException.java
> +}
오호...이런 의도라 여윽시... 한 수 배웁니다

2023-01-19 13:09 UTC, JerryK026 approved these changes
잘 봤읍니다. 사실 저는 뭐가 뭔지 몰라서 그냥 슥 훑어보고 뭐 하려는 거구나 정도만 파악했네요 ㅎㅎ;;; 혹시 작성하실 때 참고하신 문서나 정보 같은 것들이 있으실까요?

2023-01-19 13:09 UTC, JerryK026 commented on pickly-push/src/main/java/org/pickly/push/service/TokenPushMessageService.java
> +        FirebaseMessaging.getInstance(firebaseApp).sendAsync(null);
👍

2023-01-19 13:09 UTC, JerryK026 commented on pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
> +    HANDLE_ACCESS_DENIED(403, "C006", "Access is Denied");
저희 나중에 메시지를 한글로 바꿀 수도 있을 것 같아요

2023-01-22 10:08 UTC, EunjiShin approved these changes

2023-01-22 14:13 UTC, JoeCP17 commented
푸시 관련해서 레퍼런스를 이곳저곳 많이 찾아보긴했었는데 공식문서 말고는 딱히 참고할 수 있을만한 요소들이 많이 없더라구요 ㅠㅠ FCM에 관련된 내용은 공식문서 참고했었습니다!

2023-01-25 14:45 UTC, merged